version: '3.4'
services:
    db:
        container_name: db
        image: postgres:11.16-alpine
        hostname: db
        restart: always
        ports:
            - '5432:5432'
        env_file: .env
        volumes:
            - ${POSTGRES_DATA_DIR:-./postgres-data}:/var/lib/postgresql/data:Z
            - ./deploy/pgsql/certs:/var/lib/postgresql/certs:ro
    app-dev:
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        container_name: testman-be
        volumes:
            - ~/logger/logs:/app/logs
        restart: always
        depends_on:
            - db
volumes:
    static: {}
