export enum errorMessage {
    BAD_REQUEST = 'Please enter a valid input',
    NOT_FOUND_TOKEN = 'Please enter a valid token',
    NOT_FOUND_EMAIL = 'Please enter a valid email address',
    NOT_FOUND_USER = 'User not found',
    NOT_FOUND_IMAGE = 'Image not found',
    NOT_FOUND_NUMBER_PHONE = 'Phone number is not valid',
    NOT_FOUND_ISSUE = 'Issue not found ',
    WRONG_PASSWORD = 'Password is not valid',
    EXISTED_USER = 'Existed user',
    WEAK_PASSWORD = 'Password is weak',
    TOKEN_INVALID = 'Token invalid',
    TOKEN_EXPIRED = 'Token expired',
    TOKEN_EXPIRED_ERROR = 'TokenExpiredError',
    UNAUTHORIZED = 'Unauthorized',
    INTERNAL_SERVER_ERROR = 'Internal server error',
    ID_INVALID = 'Id invalid',
    NOT_SUPPORTED_FILE = 'File format not supported',
    FILE_SIZE_ALERT = 'File size must in range of 0MB to 25MB',
    IMAGE_REQUIRED = 'Image is required',
    CONFIRM_NOT_MATCH = 'Password confim not match',
    ML_DOWN = 'Machine Learning is down',
    ML_ERROR = 'Machine Learning server error',
    NOT_FOUND_PERMISSION = 'Permission not found'
}
